# Generated by Django 3.0.7 on 2020-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='artwork',
            field=models.URLField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
