# Generated by Django 3.0.7 on 2020-07-01 21:39

from django.db import migrations
from data_files.categories import categories

def create_category(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    for category in categories:
        Category.objects.create(name=category)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_artwork'),
    ]

    operations = [
        migrations.RunPython(create_category),

    ]
