# Generated by Django 3.0.7 on 2020-07-01 23:59

from django.db import migrations
from data_files.categories import categories



class Migration(migrations.Migration):

    def create_slug(apps, schema_editor):
        Category = apps.get_model('core', 'Category')
        categories = Category.objects.all()
        for category in categories:
            category.slug = slugify(category.name)
            category.save()


    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.RunPython(create_slug),
    ]
