# Generated by Django 3.0.7 on 2020-07-01 23:59

from django.db import migrations
from data_files.categories import categories


def create_slug(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    for category in categories:
        Category.objects.create(name=category)



class Migration(migrations.Migration):


    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.RunPython(create_slug),
    ]
