categories = [
    "Action and Adventure",
    "Anthology",
    "Classic",
    "Comic and Graphic Novel",
    "Crime and Detective",
    "Drama",
    "Fable",
    "Fairy Tale",
    "Fan-Fiction",
    "Fantasy",
    "Historical Fiction",
    "Horror",
    "Humor",
    "Legend",
    "Magical Realism",
    "Mystery",
    "Mythology",
    "Realistic Fiction",
    "Romance",
    "Satire",
    "Science Fiction",
    "Short Story",
    "Suspense/Thriller",
    "Biography/Autobiography",
    "Essay",
    "Memoir",
    "Narrative Nonfiction",
    "Periodicals",
    "Reference Books",
    "Self-help Book",
    "Speech",
    "Textbook",
    "Poetry",
]